#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Jan 26 11:22:07 2021

@author: Bjorn1
"""

#1 exercise
list_numbers = [26, 54, 93, 17, 77, 31, 44, 55, 20]


def mymax(list1):
    maximum = list1[0]
    max_index = 0
    index = 0
    for item in list1:
        if item > maximum:
            maximum = item
            max_index = index
        index += 1
    return maximum, max_index

maximum_number, max_index = mymax(list_numbers)

#add the maximum number at the end of the list
#need the length of the list
#needs a variable that's the highest index number

length_list_numbers = len(list_numbers) - 1
last_position_number_list = list_numbers[length_list_numbers]

print(length_list_numbers)
print(last_position_number_list)

list_numbers[length_list_numbers] = maximum_number
list_numbers[max_index] = last_position_number_list

print(list_numbers)